# Generated by Django 3.2.12 on 2022-02-14 15:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='signature',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Type your full name below'),
        ),
    ]
