# Generated by Django 2.2.12 on 2022-02-08 17:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Mailing address'),
        ),
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Date of birth (mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Your email address'),
        ),
        migrations.AddField(
            model_name='player',
            name='firstname',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='player',
            name='zip',
            field=otree.db.models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='ZIP Code'),
        ),
    ]
