# Generated by Django 2.2.12 on 2022-02-08 18:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20220208_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accept',
            field=otree.db.models.StringField(choices=[['I APPROVE', 'I APPROVE'], ['I DO NOT APPROVE', 'I DO NOT APPROVE']], max_length=10000, null=True, verbose_name=''),
        ),
    ]
