# Generated by Django 2.2.12 on 2022-02-22 18:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_player_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=otree.db.models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Age'),
        ),
    ]
